### ISSUE TITLE
Can't run ReferenceError: 'callback' is not defined

### ISSUE THREAD

**Issue by chansuke** [rsdoiel/xlsx2json#1]
I tried to exchange Excel toJSON but it returns `Can't run ReferenceError: 'callback' is not defined`.

**Comment by rsdoiel** [comment]
I have to look into this the code is a bit stale. Thanks for the report.

**Comment by rsdoiel** [comment]
I just pushed a fixed version. Hopefully this helps.

**Comment by chansuke** [comment]
@rsdoiel Thank you

**Comment by rsdoiel** [comment]
No problem. This was just a quick project to learn a couple packages.  Ran into an interesting Go project called yesterday called [jid](https://github.com/simeji/jid), JSON Incremental Digger. If you're rendering spreadsheets as JSON (or exploring other JSON artifacts) its kinda cool to use and feel your way through the data.  All the best, Robert
